---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import the 'FAS_litters.csv' csv

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)
```

Import the same dataset usig an absolute path

```{r}
litters_df =
  read_csv("~/Desktop/Data Science/data_wragling/data/FAS_litters.csv")

litters_df =
  janitor::clean_names(litters_df)
```

Import Pups dataset

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df =
  read.csv("~/Desktop/Data Science/data_wragling/data/FAS_litters.csv")

pups_df =
  janitor::clean_names(pups_df)
```

## Look at data

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

use "View"

```{r, eval = FALSE}
view(litters_df)
```

Look at a data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df =
  read_csv("data/FAS_litters.csv",
           skip = 10,
           col_names = FALSE)
```

look at NA values.

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA", 19, ".")
  )
```

Column types

```{r}
litters_df =
  read_csv("data/FAS_litters.csv",
  col_types = cols('gd0 weight' = col_character()))
```

## Other file types

Import a xlsx file first

```{r}
mlb_df =
  read_excel("data/mlb11.xlsx")
```

Import a SAS file

```{r}
pulse_df =
  read_sas("data/public_pulse_data.sas7bdat")
```

## Base R...

don't do this

```{r, eval = FALSE}
litters_df =
  read.csv("data/FAS_litters.csv")
```


## Export data

```{r}
litters_df =
  read.csv("data/FAS_litters.csv")

litters_df_cleaned =
  janitor::clean_names(
    litters_df_cleaned
  )

write_csv(litters_df_cleaned, "data/litters_cleaned.csv")
```
